name: comfortable_attendance
description: "تطبيق هاتف مبرمج بflutter لتقييم حضور العمال خلال كل شهر "
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  google_fonts: 
  shared_preferences: 
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
